// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Header$Web from "./Header.bs.js";

function App(Props) {
  return React.createElement(Header$Web.make, {});
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
