// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as App$Web from "./App.bs.js";
import * as ReactDom from "react-dom";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Css from "@emotion/css";

Css.injectGlobal("\n* {\n    margin: 0;\n    padding: 0;\n    box-sizing: border-box;\n}\nbody {\n  font-family: 'Poppins', sans-serif;\n}");

ReactDom.render(React.createElement(React.StrictMode, {
          children: React.createElement(App$Web.make, {})
        }), Belt_Option.getExn(Caml_option.nullable_to_opt(document.querySelector("#root"))));

if (import.meta.hot) {
  import.meta.hot.accept();
}

export {
  
}
/*  Not a pure module */
